name: codecoverage
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      
      - name: Install uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0

      - name: Set up Python 3.11
        run: uv python install 3.11

      - name: "Build"
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            uv sync --all-extras --upgrade
          else
            uv sync --all-extras --frozen
          fi

      - name: Generate coverage report
        run: |
          git clone --depth 1 https://github.com/equinor/xtgeo-testdata ../xtgeo-testdata
          uv run pytest -n auto tests --disable-warnings --cov-report=xml:fmu-tools.xml;

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@0b35c9ecc4f0529d0eb674914510c22f85b196b4 # v7.1.0
        with:
          files: fmu-tools.xml
